export const mockMomentsData = [
    { id: 1, image: require('../images/moments/rectangle68.png') },
    { id: 2, image: require('../images/moments/rectangle1.png') },
    { id: 3, image: require('../images/moments/rectangle2.png') },
    { id: 4, image: require('../images/moments/rectangle3.png') },
    { id: 5, image: require('../images/moments/rectangle4.png') },
    { id: 6, image: require('../images/moments/rectangle5.png') },
    { id: 7, image: require('../images/moments/rectangle6.png') },
    { id: 8, image: require('../images/moments/rectangle7.png') },
    { id: 9, image: require('../images/moments/rectangle8.png') },
    { id: 10, image: require('../images/moments/rectangle9.png') },
    { id: 11, image: require('../images/moments/rectangle10.png') },
    { id: 12, image: require('../images/moments/rectangle11.png') },
    { id: 13, image: require('../images/moments/rectangle12.png') },
    { id: 14, image: require('../images/moments/rectangle13.png') },
    { id: 15, image: require('../images/moments/rectangle14.png') },
    { id: 16, image: require('../images/moments/rectangle15.png') },
    { id: 17, image: require('../images/moments/rectangle16.png') },
    { id: 18, image: require('../images/moments/rectangle17.png') },
    { id: 19, image: require('../images/moments/rectangle18.png') },
    { id: 20, image: require('../images/moments/rectangle19.png') },
    { id: 21, image: require('../images/moments/rectangle20.png') }
];
